spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: saeed
    password: root
    driver-class-name: org.postgresql.Driver
  jackson:
    deserialization:
      unwrap_root_value: true

logging:
  level:
    root: info

jwt:
  sign-key: 123
  token-prefix: Token
  valid-time: 1000
  issuer: core-app